In [241]:
import pandas as pd

data = pd.read_csv('dataset.csv')

df = pd.DataFrame(data)

In [ ]:
df.head()

,Founder_Type,Economic_Climate,Founder_Age,Founder_Experience_Years,Industry,Funding_Stage,Work_Mode,Team_Size,Startup_Age_Months,Weekly_Work_Hours,...,Founder_Burnout_Flag,Monthly_Revenue_Growth_Percent,Runway_Months_Remaining,Product_Market_Fit_Score,Employee_Turnover_Percent,Work_Life_Balance_Score,Seeks_Mental_Health_Support,Shutdown_Probability,Shutdown_Risk,Startup_Failure_Flag
0,Serial Entrepreneur,Recession,31,12,E-commerce,Seed,Remote,14,99,48.5,...,0,-5.1,5.6,7.8,30.0,9.7,No,0.082,Low,0
1,Calm Operator,Recession,30,0,FinTech,Bootstrapped,Remote,6,47,48.6,...,0,2.7,8.4,2.3,14.4,10.0,No,0.490,Medium,0
2,Burned-Out Operator,Stable Economy,28,3,ClimateTech,Bootstrapped,Hybrid,5,59,68.8,...,0,16.3,4.4,1.0,41.5,4.0,No,0.905,High,1
3,Chaotic Innovator,Stable Economy,32,2,EdTech,Series A,Office,74,143,81.5,...,0,-1.4,31.5,4.0,39.4,5.1,No,0.233,Low,0
4,Growth Obsessed Founder,Stable Economy,35,1,SaaS,Pre-Seed,Hybrid,9,11,78.6,...,0,21.6,7.0,5.2,36.5,4.2,No,0.716,High,1

In [205]:
df_Founder_Burnout_Flag['Seeks_Mental_Health_Support'].unique()

array(['No', 'Yes'], dtype=object)

In [206]:
df_Founder_Burnout_Flag = df[['Economic_Climate', 'Founder_Age', 'Founder_Experience_Years', 'Industry', 'Funding_Stage', 'Work_Mode', 'Team_Size', 'Startup_Age_Months', 'Weekly_Work_Hours', 'Monthly_Revenue_Growth_Percent', 'Runway_Months_Remaining', 'Product_Market_Fit_Score', 'Employee_Turnover_Percent', 'Work_Life_Balance_Score', 'Seeks_Mental_Health_Support', 'Founder_Burnout_Flag']]

In [207]:
X = df_Founder_Burnout_Flag.drop(columns=['Founder_Burnout_Flag'])
y = df_Founder_Burnout_Flag['Founder_Burnout_Flag']

In [244]:
y

0        0
1        0
2        0
3        0
4        0
        ..
49995    0
49996    0
49997    0
49998    0
49999    0
Name: Founder_Burnout_Flag, Length: 50000, dtype: int64

In [273]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [210]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, f1_score, confusion_matrix, accuracy_score

In [211]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd

transformer = ColumnTransformer(
    transformers=[
        ('tf1', OneHotEncoder(sparse_output=False), ['Economic_Climate', 'Industry', 'Funding_Stage', 'Work_Mode', 'Seeks_Mental_Health_Support']),
        ('tf2', StandardScaler(), ['Founder_Age', 'Founder_Experience_Years', 'Team_Size', 'Startup_Age_Months', 'Weekly_Work_Hours', 'Monthly_Revenue_Growth_Percent','Runway_Months_Remaining','Product_Market_Fit_Score','Employee_Turnover_Percent','Work_Life_Balance_Score'])
    ],
    remainder='drop'
)

In [279]:
# final model is LogisticRegression, so we build there pipeline for automation

from sklearn.pipeline import Pipeline

pipe = Pipeline(
    [
        ('Preprocessing', transformer),
        ('lr', LogisticRegression())
    ]
)

pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)

In [236]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9524
F1 score: 0.9516175544507576
              precision    recall  f1-score   support

           0       0.97      0.98      0.97     13407
           1       0.80      0.74      0.77      1593

    accuracy                           0.95     15000
   macro avg       0.88      0.86      0.87     15000
weighted avg       0.95      0.95      0.95     15000

[[13107   300]
 [  414  1179]]

In [248]:
df_startup_burnout = df[[
'Founder_Type',
'Economic_Climate',
'Founder_Age',
'Founder_Experience_Years',
'Industry',
'Funding_Stage',
'Work_Mode',
'Team_Size',
'Startup_Age_Months',
'Weekly_Work_Hours',
'Founder_Burnout_Flag',
'Monthly_Revenue_Growth_Percent',
'Runway_Months_Remaining',
'Product_Market_Fit_Score',
'Employee_Turnover_Percent',
'Work_Life_Balance_Score',
'Seeks_Mental_Health_Support',
'Startup_Failure_Flag'
]]

X = df_startup_burnout.drop(columns=['Startup_Failure_Flag'])
y = df_startup_burnout['Startup_Failure_Flag']

In [249]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        (
            'tf1',
            OneHotEncoder(sparse_output=False),
            [
                'Founder_Type',
                'Economic_Climate',
                'Industry',
                'Funding_Stage',
                'Work_Mode',
                'Seeks_Mental_Health_Support'
            ]
        ),
        (
            'tf2',
            StandardScaler(),
            [
                'Founder_Age',
                'Founder_Experience_Years',
                'Team_Size',
                'Startup_Age_Months',
                'Weekly_Work_Hours',
                'Founder_Burnout_Flag',
                'Monthly_Revenue_Growth_Percent',
                'Runway_Months_Remaining',
                'Product_Market_Fit_Score',
                'Employee_Turnover_Percent',
                'Work_Life_Balance_Score'
            ]
        )
    ],
    remainder='drop'
)

In [250]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [271]:
pipe2 = Pipeline(
    [
        ('Preprocessing', transformer),
        ('model', XGBClassifier(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
        eval_metric='logloss'
    ))
    ]
)

In [274]:
pipe2.fit(x_train, y_train)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('tf1',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Founder_Type',
                                                   'Economic_Climate',
                                                   'Industry', 'Funding_Stage',
                                                   'Work_Mode',
                                                   'Seeks_Mental_Health_Support']),
                                                 ('tf2', StandardScaler(),
                                                  ['Founder_Age',
                                                   'Founder_Experience_Years',
                                                   'Team_Size',
                                                   'Startup_Age_Months',
                                                   'Weekly_Work_Hours',
                                                   'Founder_Burnout_F...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=500, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [275]:
y_pred = pipe2.predict(x_test)

In [276]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred, average='weighted'))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8784666666666666
F1 score: 0.8763181479074971
              precision    recall  f1-score   support

           0       0.91      0.94      0.92     11466
           1       0.77      0.69      0.73      3534

    accuracy                           0.88     15000
   macro avg       0.84      0.81      0.83     15000
weighted avg       0.88      0.88      0.88     15000

[[10722   744]
 [ 1079  2455]]

In [277]:
x_train

,Founder_Type,Economic_Climate,Founder_Age,Founder_Experience_Years,Industry,Funding_Stage,Work_Mode,Team_Size,Startup_Age_Months,Weekly_Work_Hours,Founder_Burnout_Flag,Monthly_Revenue_Growth_Percent,Runway_Months_Remaining,Product_Market_Fit_Score,Employee_Turnover_Percent,Work_Life_Balance_Score,Seeks_Mental_Health_Support
38094,Calm Operator,Funding Winter,33,3,Biotech,Series A,Office,83,122,42.0,0,-4.9,14.0,6.0,27.6,10.0,No
40624,Serial Entrepreneur,Funding Winter,32,7,ClimateTech,Series A,Remote,23,41,45.3,0,-3.7,6.0,6.2,20.3,10.0,No
49425,Technical Builder,Funding Winter,36,1,ClimateTech,Series A,Office,32,113,52.0,0,-1.2,1.0,4.0,39.9,5.4,No
35734,Calm Operator,Stable Economy,32,2,Gaming,Pre-Seed,Remote,5,86,48.3,0,-10.0,15.0,7.3,26.6,10.0,No
41708,Chaotic Innovator,Stable Economy,30,3,Cybersecurity,Seed,Hybrid,24,28,65.9,0,-33.6,14.6,6.0,36.4,9.4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,Burned-Out Operator,Recession,25,0,EdTech,Pre-Seed,Remote,14,65,67.9,0,-17.0,1.0,1.3,49.4,3.6,No
44732,Technical Builder,Stable Economy,30,1,AI,Seed,Remote,25,86,62.4,0,48.1,22.3,9.1,16.9,10.0,Yes
38158,Solo Hustler,Stable Economy,27,0,Cybersecurity,Seed,Hybrid,28,125,58.1,0,-4.5,13.7,1.3,24.8,8.3,No
860,Solo Hustler,Funding Winter,44,1,E-commerce,Seed,Remote,14,26,87.1,1,-0.8,19.1,3.2,72.8,2.9,Yes
15795,Solo Hustler,Stable Economy,41,2,AI,Seed,Remote,7,2,84.8,0,20.6,4.8,3.2,32.2,3.2,No

In [278]:
import joblib

# Burnout Model
joblib.dump(pipe, 'burnout_pipe.pkl')

# Startup Failure Model
joblib.dump(pipe2, 'failure_pipe.pkl')

['failure_pipe.pkl']